### ISSUE TITLE
[BUG] Error when giving somebody a role

### ISSUE THREAD

**Issue by ItsShunya** [Shunya-sama/Shuwy#16]
When you try to give somebody a role (for example welcome role) that is higher than the bot's role, it will display a message.

**Comment by ItsShunya** [comment]
Confirmed this same error happens on adding reaction roles.

**Comment by ItsShunya** [comment]
Found full traceback error:

> Ignoring exception in on_member_join
> Traceback (most recent call last):
>   File "C:\Users\luque\.virtualenvs\Shuwy-HYdT1WkZ\lib\site-packages\discord\client.py", line 333, in _run_event
>     await coro(*args, **kwargs)
>   File "D:\Projects\Shuwy Discord Bot\Shuwy\Shuwy\cogs\Members.py", line 179, in on_member_join
>     await member.add_roles(role)
>   File "C:\Users\luque\.virtualenvs\Shuwy-HYdT1WkZ\lib\site-packages\discord\member.py", line 664, in add_roles
>     await req(guild_id, user_id, role.id, reason=reason)
>   File "C:\Users\luque\.virtualenvs\Shuwy-HYdT1WkZ\lib\site-packages\discord\http.py", line 241, in request
>     raise Forbidden(r, data)
> discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

**Comment by ItsShunya** [comment]
This issue can't be solved but we can add an error handling to display a message when this happens. Problem should be adressed to the server's admin to raise the bot permissions.
